In [13]:
#1
import numpy as np

In [44]:
#2
print (np.version.version)
print(np.show_config())

1.16.2
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Minh Duc/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Minh Duc/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Minh Duc/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\

In [11]:
#3
x=np.zeros(10)
print(x)

In [15]:
#4
print("%d bytes" % (x.size * x.itemsize))

80 bytes


In [20]:
#5
print(np.info)

<function info at 0x000001D42B9E87B8>


In [24]:
#6
y=np.zeros(10)
y[4]=1
print(y)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [26]:
#7
x=np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [28]:
#8
x=np.arange(15)
X=x[::-1]
print(X)

[14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [29]:
#9
x=np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [30]:
#10
x=np.nonzero([1,2,0,0,4,0])
print(x)

(array([0, 1, 4], dtype=int64),)


In [31]:
#11
x=np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [33]:
#12
x=np.random.random((3,3,3))
print(x)

[[[0.33394188 0.16043981 0.14855073]
  [0.50112452 0.22600661 0.10774986]
  [0.92379056 0.05306569 0.00492473]]

 [[0.44469568 0.51517252 0.38557334]
  [0.65924924 0.75638876 0.02394211]
  [0.42524983 0.14771262 0.87041002]]

 [[0.63979565 0.37395282 0.34504234]
  [0.86349694 0.50208908 0.81922206]
  [0.0221125  0.98782134 0.08758857]]]


In [35]:
#13
x=np.random.random((10,10))
print(x.max(),x.min())

0.9978718276041993 0.00010354320982319809


In [36]:
#14
x=np.random.random(30)
print(x.mean())

0.545949807673379


In [37]:
#15
x=np.ones((10,10))
x[1:-1,1:-1]=0
print (x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [38]:
#16
x=np.ones((6,6))
X=np.pad(x,pad_width=1, mode='constant', constant_values=0)
print(X)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [39]:
#17
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


In [40]:
#18
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [48]:
#19
x= np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [51]:
#20
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [55]:
#21
y = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(y)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [4]:
#22
x=np.random.random((5,5))
x= (x - np.max(x)) / (np.max(x)-np.min(x))
print(x)

[[-0.80783635 -0.39237956 -0.23116214 -0.22847459 -0.36570095]
 [-0.00120084 -0.42717202 -0.24608102 -0.93285772 -0.53399784]
 [-0.52133143 -0.44745649 -1.         -0.87801824 -0.96191084]
 [-0.26301647 -0.22045744 -0.6969057  -0.38978531 -0.95865326]
 [-0.43960832 -0.94682565 -0.09732085 -0.58452119  0.        ]]


In [5]:
#23
color = np.dtype([("r", np.ubyte, 1), ("g", np.ubyte, 1), ("b", np.ubyte, 1), ("a", np.ubyte, 1)])

In [7]:
#24
x= np.ones((5,3))@np.ones((3,2))
print (x)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [8]:
#25
x= np.arange(11)
x[(3 < x) & (x <= 8)] = -1
print(x)

[ 0  1  2  3 -1 -1 -1 -1 -1  9 10]


In [9]:
print(sum(range(5),-1)) from numpy import * print(sum(range(5),-1))

SyntaxError: invalid syntax (<ipython-input-9-b298f34a4305>, line 1)

In [15]:
#26
print(sum(range(5),-1))
from numpy import*
print(sum(range(5),-1))

9
10


In [20]:
#27
Z*Z 
2 << Z >> 2
Z <- Z 
1jZ 
Z/1/1
ZZ

SyntaxError: invalid syntax (<ipython-input-20-f0b3b92c4e52>, line 5)

In [21]:
#28
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0)) 
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\Minh Duc\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
C:\Users\Minh Duc\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until


In [22]:
#29
Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[  2.   6.  -8.   6.  -3.  -3. -10.   4.  -8.   9.]


In [27]:
#30
x=np.random.randint(0,10,10)
y=np.random.randint(0,10,10)
print(np.intersect1d(x,y))

[5 6 8]


In [28]:
#31
defaults = np.seterr(all="ignore")

In [29]:
#32
np.sqrt(-1) == np.emath.sqrt(-1)

False

In [31]:
#33
yesterday=np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today=np.datetime64('today','D')
tomorrow=np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday,today,tomorrow)

2019-08-10 2019-08-11 2019-08-12


In [41]:
#34
x=np.arange('2019-07','2019-08', dtype='datetime64[D]')
print(x)
            

['2019-07-01' '2019-07-02' '2019-07-03' '2019-07-04' '2019-07-05'
 '2019-07-06' '2019-07-07' '2019-07-08' '2019-07-09' '2019-07-10'
 '2019-07-11' '2019-07-12' '2019-07-13' '2019-07-14' '2019-07-15'
 '2019-07-16' '2019-07-17' '2019-07-18' '2019-07-19' '2019-07-20'
 '2019-07-21' '2019-07-22' '2019-07-23' '2019-07-24' '2019-07-25'
 '2019-07-26' '2019-07-27' '2019-07-28' '2019-07-29' '2019-07-30'
 '2019-07-31']


In [ ]:
#35


In [46]:
#36
x=np.random.uniform(0,10,10)
print(x-x%1)
print(np.floor(x))
print(np.ceil(x)-1)
print(x.astype(int))
print(np.trunc(x))

[3. 9. 0. 2. 5. 9. 8. 7. 5. 9.]
[3. 9. 0. 2. 5. 9. 8. 7. 5. 9.]
[3. 9. 0. 2. 5. 9. 8. 7. 5. 9.]
[3 9 0 2 5 9 8 7 5 9]
[3. 9. 0. 2. 5. 9. 8. 7. 5. 9.]


In [49]:
#37
x = np.zeros((5,5))
x += np.arange(5)
print(x)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [51]:
#38


SyntaxError: invalid character in identifier (<ipython-input-51-21c14de4d531>, line 3)

In [55]:
#39
x=np.linspace(0,1,11,endpoint=False)[1:]
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [60]:
#40
x=np.random.random((10,10))
x.sort()
print(x)

[[0.07010846 0.08122486 0.09902171 0.49577303 0.59171864 0.63219336
  0.66318462 0.78788867 0.84800955 0.92291112]
 [0.09313176 0.12033222 0.14516484 0.34308085 0.37384358 0.51064857
  0.69833609 0.76347383 0.7671298  0.85270736]
 [0.04624099 0.07445735 0.12529737 0.25463437 0.30321528 0.448581
  0.5134884  0.63597138 0.87178752 0.95906741]
 [0.04014368 0.15397749 0.5257072  0.67472985 0.79285686 0.87392924
  0.96259771 0.96612975 0.97530739 0.99944742]
 [0.02771418 0.21214172 0.30661359 0.43095193 0.46145272 0.49515826
  0.62253455 0.73707919 0.75618144 0.83559938]
 [0.1246102  0.2300961  0.29584333 0.3862062  0.39227853 0.56571551
  0.70814935 0.73278172 0.87898609 0.9603565 ]
 [0.0322993  0.11326452 0.13805594 0.15352206 0.36446589 0.36996172
  0.4436568  0.73041878 0.89031672 0.99407357]
 [0.03832249 0.11313381 0.12797506 0.34812883 0.43257861 0.45761317
  0.52940558 0.53423047 0.70201542 0.83099128]
 [0.20120055 0.23851865 0.28107468 0.35619365 0.48661515 0.49990423
  0.55097411 0

In [63]:
#41
x=np.arange(6)
np.add.reduce(x)
print(x)

[0 1 2 3 4 5]


In [67]:
#42
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(A,B)
equal=np.allclose(A,B)
print(equal)
equal1=np.array_equal(A,B)
print(equal1)

[1 1 0 0 1] [0 0 0 0 0]
False
False


In [69]:
#43
x=np.arange(8)
#immutable (read-only) 
print(x.flags.writeable())

TypeError: 'bool' object is not callable

In [ ]:
#44


In [71]:
#45
x=np.random.random(10)
x[x.argmax()]=0
print(x)

[0.79032775 0.         0.8932175  0.23971476 0.73972404 0.86810189
 0.22184148 0.08239035 0.05880957 0.54117995]


In [ ]:
#46

In [72]:
#47
X = np.arange(8)
Y = np.arange(8)
C = 1.0 / np.subtract.outer(X, Y)
print(C)

[[        inf -1.         -0.5        -0.33333333 -0.25       -0.2
  -0.16666667 -0.14285714]
 [ 1.                 inf -1.         -0.5        -0.33333333 -0.25
  -0.2        -0.16666667]
 [ 0.5         1.                 inf -1.         -0.5        -0.33333333
  -0.25       -0.2       ]
 [ 0.33333333  0.5         1.                 inf -1.         -0.5
  -0.33333333 -0.25      ]
 [ 0.25        0.33333333  0.5         1.                 inf -1.
  -0.5        -0.33333333]
 [ 0.2         0.25        0.33333333  0.5         1.                 inf
  -1.         -0.5       ]
 [ 0.16666667  0.2         0.25        0.33333333  0.5         1.
          inf -1.        ]
 [ 0.14285714  0.16666667  0.2         0.25        0.33333333  0.5
   1.                 inf]]


In [ ]:
#49
np.set_printoptions()